-- Insercion de los datos dentro de las tablas 

BULK INSERT foodtrucks
FROM 'C:\Users\juanc\OneDrive\Documentos\JUAN CARLOS\ESTUDIOS\CIENCIA DE DATOS\M2 SQL\HOMEWORKS\LECTURE 1\FOODTRUCKS\DATA\foodtrucks.csv'
WITH (
FORMAT = 'CSV',
FIRSTROW = 2,
FIELDTERMINATOR = ',',
ROWTERMINATOR = '0x0A'
);

SELECT * FROM foodtrucks;

BULK INSERT locations
FROM 'C:\Users\juanc\OneDrive\Documentos\JUAN CARLOS\ESTUDIOS\CIENCIA DE DATOS\M2 SQL\HOMEWORKS\LECTURE 1\FOODTRUCKS\DATA\locations.csv'
WITH (
FORMAT = 'CSV',
FIRSTROW = 2,
FIELDTERMINATOR = ',',
ROWTERMINATOR = '0x0A'
);

SELECT * FROM locations;

BULK INSERT order_items
FROM 'C:\Users\juanc\OneDrive\Documentos\JUAN CARLOS\ESTUDIOS\CIENCIA DE DATOS\M2 SQL\HOMEWORKS\LECTURE 1\FOODTRUCKS\DATA\order_items.csv'
WITH (
FORMAT = 'CSV',
FIRSTROW = 2,
FIELDTERMINATOR = ',',
ROWTERMINATOR = '0x0A'
);

SELECT * FROM order_items;

BULK INSERT orders
FROM 'C:\Users\juanc\OneDrive\Documentos\JUAN CARLOS\ESTUDIOS\CIENCIA DE DATOS\M2 SQL\HOMEWORKS\LECTURE 1\FOODTRUCKS\DATA\orders.csv'
WITH (
FORMAT = 'CSV',
FIRSTROW = 2,
FIELDTERMINATOR = ',',
ROWTERMINATOR = '0x0A'
);

SELECT * FROM orders;

BULK INSERT products
FROM 'C:\Users\juanc\OneDrive\Documentos\JUAN CARLOS\ESTUDIOS\CIENCIA DE DATOS\M2 SQL\HOMEWORKS\LECTURE 1\FOODTRUCKS\DATA\products.csv'
WITH (
FORMAT = 'CSV',
FIRSTROW = 2,
FIELDTERMINATOR = ',',
ROWTERMINATOR = '0x0A'
);

SELECT * FROM products;

SELECT COUNT(*) FROM foodtrucks; -- 2 filas
SELECT COUNT(*) FROM locations; --2 filas
SELECT COUNT(*) FROM order_items; --3 filas
SELECT COUNT(*) FROM orders; --2 filas

